Random seed: 7684003357565885625
---------------- Starting Your Algo --------------------
Configuring your custom algo strategy...
Performing turn 0 of your custom algo strategy
Could not spawn DF at location [12, 11]. Not enough resources.
Traceback (most recent call last):
  File "C:\Users\TheDonut\Documents\Berkeley\terminal\C1GamesStarterKit\staticstrat\algo_strategy.py", line 281, in <module>
    algo.start()
  File "C:\Users\TheDonut\Documents\Berkeley\terminal\C1GamesStarterKit\staticstrat\gamelib\algocore.py", line 74, in start
    self.on_turn(game_state_string)
  File "C:\Users\TheDonut\Documents\Berkeley\terminal\C1GamesStarterKit\staticstrat\algo_strategy.py", line 69, in on_turn
    self.my_strategy(game_state)
  File "C:\Users\TheDonut\Documents\Berkeley\terminal\C1GamesStarterKit\staticstrat\algo_strategy.py", line 88, in my_strategy
    self.adaptive_defences(game_state)
  File "C:\Users\TheDonut\Documents\Berkeley\terminal\C1GamesStarterKit\staticstrat\algo_strategy.py", line 107, in adaptive_defences
    game_state.attempt_spawn(DESTRUCTOR, location)
  File "C:\Users\TheDonut\Documents\Berkeley\terminal\C1GamesStarterKit\staticstrat\gamelib\game_state.py", line 376, in attempt_spawn
    if self.can_spawn(unit_type, location, 1):
  File "C:\Users\TheDonut\Documents\Berkeley\terminal\C1GamesStarterKit\staticstrat\gamelib\game_state.py", line 324, in can_spawn
    if not self.game_map.in_arena_bounds(location):
  File "C:\Users\TheDonut\Documents\Berkeley\terminal\C1GamesStarterKit\staticstrat\gamelib\game_map.py", line 93, in in_arena_bounds
    row_size = y + 1
TypeError: can only concatenate list (not "int") to list
